# 使用 Python 基础镜像
FROM python:3.9-alpine

# 设置工作目录
WORKDIR /usr/src/app

# 复制 requirements.txt 并安装依赖
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --upgrade Flask itsdangerous
RUN pip install gunicorn

# 复制应用文件到容器中
COPY app.py ./
COPY spider.py ./
COPY databaseLib.py ./
COPY key.py ./
COPY sqlite_storage/notification.db ./sqlite_storage/notification.db

# 暴露端口 80
EXPOSE 80

# 启动 cron 服务和 app.py
CMD ["gunicorn", "-b", "0.0.0.0:80", "app:app"]